### ISSUE TITLE
Download error when trying to download from huggingface

### ISSUE THREAD

**Issue by linzhiqiu** [ShareGPT4Omni/ShareGPT4Video#7]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 2592, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 2264, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 1909, in dataset_module_factory
    raise e1 from None
  File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 1897, in dataset_module_factory
    ).get_module()
  File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 1275, in get_module
    module_name, default_builder_kwargs = infer_module_for_data_files(
  File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 597, in infer_module_for_data_files
    raise DataFilesNotFoundError("No (supported) data files found" + (f" in {path}" if path else ""))
datasets.exceptions.DataFilesNotFoundError: No (supported) data files found in ShareGPT4Video/ShareGPT4Video
```

Any hint on how to resolve it? Am I missing an official download instruction?

**Comment by Wiselnn570** [comment]
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 2592, in load_dataset
>     builder_instance = load_dataset_builder(
>   File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 2264, in load_dataset_builder
>     dataset_module = dataset_module_factory(
>   File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 1909, in dataset_module_factory
>     raise e1 from None
>   File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 1897, in dataset_module_factory
>     ).get_module()
>   File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 1275, in get_module
>     module_name, default_builder_kwargs = infer_module_for_data_files(
>   File "/home/zhiqiul/miniconda3/envs/share4video/lib/python3.10/site-packages/datasets/load.py", line 597, in infer_module_for_data_files
>     raise DataFilesNotFoundError("No (supported) data files found" + (f" in {path}" if path else ""))
> datasets.exceptions.DataFilesNotFoundError: No (supported) data files found in ShareGPT4Video/ShareGPT4Video
> ```
> 
> 
>     
>   
> 
> Any hint on how to resolve it? Am I missing an official download instruction?

Hi, @linzhiqiu!
you can refer to this code to download the dataset：
```python
from huggingface_hub import snapshot_download
snapshot_download(repo_id='ShareGPT4Video/ShareGPT4Video', repo_type="dataset", cache_dir='/path/to/your/folder')
```
For more details, please visit [https://huggingface.co/docs/huggingface_hub/v0.21.4/guides/download](https://huggingface.co/docs/huggingface_hub/v0.21.4/guides/download)

best wishes.
